import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { BottomNav } from "@/components/BottomNav";
import { AuthGate } from "@/components/AuthGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-100`}>
        <div
          className="relative mx-auto h-dvh max-w-[480px] overflow-hidden bg-white"
          style={{ transform: "translateZ(0)" }}
        >
          <div className="h-full overflow-y-auto">
            <AuthGate>{children}</AuthGate>
          </div>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
